# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# bgggnmmAdd steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Firstjob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(pipelineLevelvariable)
  - job: SecondJob
    steps:
    - bash: echo Build FirstJob
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevdeployJob
    steps:
    - bash: echo DevdeployJob
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployjob
    steps:
    - bash: echo QADeployjob
- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  jobs:
  - job: ProdDeployjob
    steps:
    - bash: echo ProdDeployjob
    - bash: echo "This is to test webhook"

